kind: Service 
apiVersion: v1 
metadata:
  name: application1-service 
spec:
  type: NodePort

  selector:
    app: application1

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30163
      port: 3000 
      targetPort: 3000
